In [6]:
import numpy as np
from MultipoleTransformations import translation_matrix
from MultipoleFields import HarmonicField as HF
np.set_printoptions(precision=3)

In [30]:
l1max = 3
l2max = l1max
m = 1
sign_z = 1
regreg = 1
kd = 0.3
T1 = translation_matrix(l1max, l2max, m, kd, sign_z, regreg)
T2 = translation_matrix(l2max, l1max, m, 2*kd, sign_z, regreg)

In [31]:
np.isclose(np.dot(T1, T1), T2)

array([[ True, False, False,  True,  True, False],
       [False, False, False,  True, False, False],
       [False, False, False, False, False, False],
       [ True,  True, False,  True, False, False],
       [ True, False, False, False, False, False],
       [False, False, False, False, False, False]], dtype=bool)

In [32]:
np.dot(np.dot(T1, T1), np.linalg.inv(T2))

array([[  1.000e+00 +0.000e+00j,   1.075e-05 +0.000e+00j,
          5.287e-05 +0.000e+00j,   0.000e+00 +5.012e-08j,
          0.000e+00 -1.097e-07j,   0.000e+00 -1.593e-06j],
       [  2.499e-05 +0.000e+00j,   1.000e+00 +0.000e+00j,
          1.362e-03 +0.000e+00j,   0.000e+00 +2.041e-06j,
          0.000e+00 +5.492e-06j,   0.000e+00 -8.954e-08j],
       [  3.670e-04 +0.000e+00j,   4.068e-03 +0.000e+00j,
          1.020e+00 +0.000e+00j,   0.000e+00 +3.368e-05j,
          0.000e+00 +1.214e-04j,   0.000e+00 +1.988e-04j],
       [  0.000e+00 +5.012e-08j,   0.000e+00 -1.097e-07j,
          0.000e+00 -1.593e-06j,   1.000e+00 +0.000e+00j,
          1.075e-05 +0.000e+00j,   5.287e-05 +0.000e+00j],
       [  0.000e+00 +2.041e-06j,   0.000e+00 +5.492e-06j,
          0.000e+00 -8.954e-08j,   2.499e-05 +0.000e+00j,
          1.000e+00 +0.000e+00j,   1.362e-03 +0.000e+00j],
       [  0.000e+00 +3.368e-05j,   0.000e+00 +1.214e-04j,
          0.000e+00 +1.988e-04j,   3.670e-04 +0.000e+00j,
         

In [9]:
field = HF(np.arange(16, dtype=np.complex128)[:,np.newaxis], 2)

In [11]:
field.get_coef_at(-2)

array([ 3, 11])

In [12]:
from numpy.testing import assert_array_almost_equal

In [33]:
a = np.random.rand(10,10)+ 5*np.random.rand(10,10)*1j
da = np.zeros(a.shape,dtype=np.complex128)
da[3,5] += 1e-4j
assert_array_almost_equal(a, a+da)

AssertionError: 
Arrays are not almost equal to 6 decimals

(mismatch 1.0%)
 x: array([[ 0.097468+4.699261j,  0.135367+0.39459j ,  0.327096+0.050843j,
         0.821074+1.285499j,  0.953921+2.474666j,  0.996419+2.358046j,
         0.002304+3.209785j,  0.583478+3.051965j,  0.818440+2.598294j,...
 y: array([[ 0.097468+4.699261j,  0.135367+0.39459j ,  0.327096+0.050843j,
         0.821074+1.285499j,  0.953921+2.474666j,  0.996419+2.358046j,
         0.002304+3.209785j,  0.583478+3.051965j,  0.818440+2.598294j,...